{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mylib.fullname" . }}-data
  labels:
    {{- include "mylib.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if and .Values.persistence.books.enabled (not .Values.persistence.books.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mylib.fullname" . }}-books
  labels:
    {{- include "mylib.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.books.accessMode }}
  {{- if .Values.persistence.books.storageClass }}
  storageClassName: {{ .Values.persistence.books.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.books.size }}
{{- end }}
